#!/bin/bash

N="rpi"
MN=""

if [ $# -eq 0 ]

then
    for i in $(seq -w 1 18) ; do
        MN=$N$i
        ping -c 1 $MN>/dev/null
        if [ $? -eq 0 ]
        then
            echo $MN : alive
        else
            echo $MN : dead
        fi
    done
else
    for j in "$@" ; do
        ping -c 1 $j>/dev/null
        if [ $? -eq 0 ]
        then
            echo $j : alive
        else
            echo $j : dead
        fi
    done
fi
